name: "Qute Bot"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 2 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "Install npm dependencies"
        run: npm install
      - name: "Run code"
        run: node index.js
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
